version: '2'
services:
  postgres:
    image: postgres:10.16
    restart: unless-stopped
    environment:
      POSTGRES_DB: nhco_policy
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
